{
  "NServiceBus.MessageId": "08e22369-51c0-47f2-a338-ac9801542e9f",
  "NServiceBus.MessageIntent": "Send",
  "NServiceBus.ConversationId": "b0fdce18-db03-43b9-93ae-ac9801542e9f",
  "NServiceBus.CorrelationId": "08e22369-51c0-47f2-a338-ac9801542e9f",
  "NServiceBus.ReplyToAddress": "ClientUI",
  "NServiceBus.OriginatingMachine": "IT-CR-ZF-0103",
  "NServiceBus.OriginatingEndpoint": "ClientUI",
  "$.diagnostics.originating.hostid": "a293edc154b9e023c189c20060d12e2e",
  "NServiceBus.ContentType": "text\/xml",
  "NServiceBus.EnclosedMessageTypes": "Messages.Commands.PlaceOrder, Messages, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
  "NServiceBus.Version": "7.4.4",
  "NServiceBus.TimeSent": "2020-12-21 20:38:33:911264 Z",
  "NServiceBus.ExceptionInfo.ExceptionType": "System.Exception",
  "NServiceBus.Retries.Timestamp": "2020-12-21 20:40:37:096521 Z",
  "NServiceBus.ExceptionInfo.HelpLink": null,
  "NServiceBus.ExceptionInfo.Message": "BOOM",
  "NServiceBus.ExceptionInfo.Source": "Sales",
  "NServiceBus.ExceptionInfo.StackTrace": "System.Exception: BOOM\r\n   at Sales.Handlers.PlaceOrderHandler.Handle(PlaceOrder message, IMessageHandlerContext context) in C:\\Users\\Nathalie Rojas\\source\\repos\\RetailDemo\\Sales\\Handlers\\PlaceOrderHandler.cs:line 21\r\n   at lambda_method(Closure , Object , Object , IMessageHandlerContext )\r\n   at NServiceBus.Pipeline.MessageHandler.Invoke(Object message, IMessageHandlerContext handlerContext) in \/_\/src\/NServiceBus.Core\/Pipeline\/Incoming\/MessageHandler.cs:line 43\r\n   at NServiceBus.InvokeHandlerTerminator.<Terminate>d__0.MoveNext() in \/_\/src\/NServiceBus.Core\/Pipeline\/Incoming\/InvokeHandlerTerminator.cs:line 33\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in \/_\/src\/NServiceBus.Core\/Pipeline\/Incoming\/LoadHandlersConnector.cs:line 48\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.ScheduledTaskHandlingBehavior.<Invoke>d__1.MoveNext() in \/_\/src\/NServiceBus.Core\/Scheduling\/ScheduledTaskHandlingBehavior.cs:line 22\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.DeserializeMessageConnector.<Invoke>d__1.MoveNext() in \/_\/src\/NServiceBus.Core\/Pipeline\/Incoming\/DeserializeMessageConnector.cs:line 33\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in \/_\/src\/NServiceBus.Core\/Performance\/Statistics\/ProcessingStatisticsBehavior.cs:line 25\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.TransportReceiveToPhysicalMessageConnector.<Invoke>d__1.MoveNext() in \/_\/src\/NServiceBus.Core\/Pipeline\/Incoming\/TransportReceiveToPhysicalMessageConnector.cs:line 37\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in \/_\/src\/NServiceBus.Core\/Pipeline\/MainPipelineExecutor.cs:line 45\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__10.MoveNext() in \/_\/src\/NServiceBus.Core\/Transports\/Learning\/LearningTransportMessagePump.cs:line 279",
  "NServiceBus.TimeOfFailure": "2020-12-21 20:41:08:301303 Z",
  "NServiceBus.ExceptionInfo.Data.Message type": "Messages.Commands.PlaceOrder",
  "NServiceBus.ExceptionInfo.Data.Handler type": "Sales.Handlers.PlaceOrderHandler",
  "NServiceBus.ExceptionInfo.Data.Handler start time": "2020-12-21 20:41:08:292372 Z",
  "NServiceBus.ExceptionInfo.Data.Handler failure time": "2020-12-21 20:41:08:293369 Z",
  "NServiceBus.ExceptionInfo.Data.Message ID": "08e22369-51c0-47f2-a338-ac9801542e9f",
  "NServiceBus.ExceptionInfo.Data.Transport message ID": "65d030ef-0fb8-4840-b898-5b2aaeec2bd8",
  "NServiceBus.FailedQ": "Sales",
  "NServiceBus.ProcessingMachine": "IT-CR-ZF-0103",
  "NServiceBus.ProcessingEndpoint": "Sales",
  "$.diagnostics.hostid": "efb0c9b58424f60336cb527e87beaae6",
  "$.diagnostics.hostdisplayname": "IT-CR-ZF-0103"
}